name: FactionsExtras
version: ${project.version}
main: me.ufo.factions.extras.Extras
depend: [ Factions, Architect ]
softdepend: [ ShopGUIPlus, Vault, WorldEdit, FastAsyncWorldEdit ]
commands:
  tools:
  genbuckets:
    aliases: [ gb, gen, genbucket ]
  chunkbusters:
